# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "0.0.0.0" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Jason Vance
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "portfolio of Projects for web deveopment" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Developer, Attorney, Dad</h1>
  header_text_feature_image:
  #footer_text: >
   

  # Icons
  rss: false
  email_address: jbvance@gmail.com
  behance:
  bitbucket:
  #dribbble: "joeykirk"
  #facebook: "joeykirk"
  #flickr:
  github: "jbvance"
  google_plus:
  #instagram: "joeykirk"
  linkedin:  https://www.linkedin.com/in/jason-vance-58a03223
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: #"joeykirk"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-89151128-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
